change-log-file=src/main/resources/db/changelog/v1/liquibase-out.xml
url=jdbc:postgresql://localhost:5432/oris_semester_work1_servlets
currentSchema=forum
username=postgres
password=postgres
driver=org.postgresql.Driver
defaultSchemaName=forum