server:
  port: 8080


spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: "${APP_DB_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${APP_DB_USERNAME:postgres}"
    password: "${APP_DB_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    suffix: .ftl

  mail:
    host: "${APP_MAIL_HOST:smtp.gmail.com}"
    port: "${APP_MAIL_PORT:465}"
    username: "${APP_MAIL_USERNAME:}"
    password: "${APP_MAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000
          ssl:
            enable: true


mail:
  sender: "${APP_MAIL_SENDER:Test Application}"
  from: "${APP_MAIL_FROM:${spring.mail.username}}"
  subject: "${APP_MAIL_SUBJECT:Please read me that's not a virus really bro}"
  content: "${APP_MAIL_CONTENT:Dear $name, please verify your mail: <a href=$url>VERIFY</a>}"
  base-url: "${APP_BASE_URL:http://localhost:8080}"
  verification-enabled: "${MAIL_VERIFICATION_ENABLED:false}"
