server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    port: 465
    username: "пупупу@gmail.com"
    password: "пароль пароль"
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000
          ssl:
            enable: true


mail:
  sender: Test Application
  from: ${spring.mail.username}
  subject: "Please read me that's not a virus really bro"
  content: "Dear $name, please verify your mail: <a href=$url>VERIFY</a>"
  base-url: http://localhost:8080

