spring.database=POSTGRESQL
spring.datasource.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${APP_DB_USERNAME:postgres}
spring.datasource.password=${APP_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
